---
- name: Install all the needed packages
  hosts: all
  tags:
    - install_packages
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install tcsh
      apt:
        name: tcsh
    - name: install ufw
      apt:
        name: ufw
    - name: install python-apt
      apt:
        name: python-apt
    - name: install aptitude
      apt:
        name: aptitude
    - name: install zip
      apt:
        name: zip
    - name: install unzip
      apt:
        name: unzip

- name: Perform system update
  hosts: all
  tags:
    - system_upgrade
  tasks:
    - name: apt upgrade
      apt:
        update_cache: yes
        upgrade: full
        cache_valid_time: 3600

- name: Configure restrictive firewalling
  hosts: all
  tags:
    - configure_firewall
  tasks:
    - name: install ufw
      apt:
        name: ufw
    - name: set up ufw to deny all
      ufw: state=enabled policy=deny
    - name: reject auth inquiries
      ufw: rule=reject port=auth
    - name: allow ssh traffic
      ufw: rule=allow name=OpenSSH
    - name: allow tomcat traffic, but only for ipv4 from local net
      command: ufw allow from 192.168.0.0/16 to any port 8443

- name: Set up local mailserver subsystem
  hosts: all
  tags:
    - local_mailserver_and_clients
  tasks:
    - name: install alpine mail reader
      apt:
        name: alpine
    - name: install mutt mail reader
      apt:
        name: mutt
    - name: install postfix
      apt:
        name: postfix
    - name: install libsasl2-modules
      apt:
        name: libsasl2-modules
    - name: install mail command line
      apt:
        name: bsd-mailx

    - name: Set Postfix option hostname
      debconf: name=postifx question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"

    - name: Set Postfix option type as local only site
      debconf: name=postfix question="postfix/main_mailer_type" value="'Local only'" vtype="string"

    - name: Install Postfix
      apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
      with_items:
        - postfix
        - mailutils

- name: Set up mysql subsystem
  hosts: all
  tags:
    - mysql_server_and_client
  tasks:
    - name: install mysql server
      apt:
        name: mysql-server
    - name: install mysql client
      apt:
        name: mysql-client

- name: Set up tomcat subsystem
  hosts: all
  tags:
    - tomcat_subsystem
  tasks:
    - name: install jdk headless
      apt:
        name: default-jdk-headless
    - name: install tomcat 8
      apt:
        name: tomcat8
